build:
  lint-and-test:
    image: node:5
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i
      - npm run postinstall
      - npm run lint
      - npm run lint-style
      - npm test

  sync-repo:
    image: node:5
    commands:
      - git pull --ff-only origin master
    when:
      branch: master

  generate-changelog:
    image: ruby
    environment:
      CHANGELOG_GITHUB_TOKEN: $$CHANGELOG_GITHUB_TOKEN
    commands:
      - gem install github_changelog_generator
      - github_changelog_generator
      - git add CHANGELOG.md
      - if ! git diff-index --quiet HEAD -- CHANGELOG.md; then
          git config --global user.name "nemobot";
          git config --global user.email "our-bots@buildo.io";
          git commit -m "Update CHANGELOG.md [skip ci]";
          git push origin master;
        fi
    when:
      branch: master

  publishReleaseOnGitHub:
    image: node:5
    environment:
      GITHUB_TOKEN: $$CHANGELOG_GITHUB_TOKEN
    commands:
      - node ./publishReleaseOnGitHub.js
    when:
      branch: master

  generate-readmes:
    image: node:5
    commands:
      - npm run generate-all-readmes
      - git add src/**/README.md
      - if ! git diff-index --quiet HEAD -- src/**/README.md; then
          git config --global user.name "nemobot";
          git config --global user.email "our-bots@buildo.io";
          git commit -m "Update READMES [skip CI]";
          git push origin master;
        fi
    when:
      branch: master

  gh-pages-build:
    image: node:5
    commands:
      - if [ "$$BRANCH" != "master" ]; then
          npm run generate-all-readmes;
          npm run build-showroom;
        fi

  gh-pages:
    image: node:5
    commands:
      - git config --global user.email "ci@buildo.io"
      - git config --global user.name "Drone CI"
      - npm run deploy-showroom
    when:
      branch: master

cache:
  mount:
    - /drone/.npm
