build:
  react-components:
    image: quay.io/buildo/node5-npm3
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
    commands:
      - npm i
      - npm run lint
      - npm run build

  gh-pages:
    image: quay.io/buildo/node5-npm3
    commands:
      - git fetch --no-tags origin +refs/heads/gh-pages
      - git checkout gh-pages
      - git pull
      - git config --global user.email "ci@buildo.io"
      - git config --global user.name "Drone CI"
      - git merge master --no-edit
      - npm run deploy-showroom
    when:
      branch: master

  generate-changelog:
    image: ruby
    environment:
      CHANGELOG_GITHUB_TOKEN: $$CHANGELOG_GITHUB_TOKEN
    commands:
      - gem install github_changelog_generator
      - github_changelog_generator
      - git add CHANGELOG.md
      - if ! git diff-index --quiet HEAD -- CHANGELOG.md; then
          git fetch --no-tags origin +refs/heads/$$BRANCH;
          git config --global user.name "nemobot";
          git config --global user.email "our-bots@buildo.io";
          git checkout $$BRANCH;
          git add CHANGELOG.md;
          git commit -m "Update CHANGELOG.md [skip ci]";
          git push origin $$BRANCH;
        fi
    when:
      branch: master

cache:
  mount:
    - /drone/.npm
