build:
  react-components:
    image: quay.io/buildo/node5-npm3
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
    commands:
      - npm i
      - npm test

  generate-changelog:
    image: ruby
    environment:
      CHANGELOG_GITHUB_TOKEN: $$CHANGELOG_GITHUB_TOKEN
    commands:
      - gem install github_changelog_generator
      - github_changelog_generator
      - git add CHANGELOG.md
      - if ! git diff-index --quiet HEAD -- CHANGELOG.md; then
          git config --global user.name "nemobot";
          git config --global user.email "our-bots@buildo.io";
          git commit -m "Update CHANGELOG.md [skip ci]";
          git push origin master;
        fi
    when:
      branch: master

  generate-readmes:
    image: quay.io/buildo/node5-npm3
    commands:
      - npm run generate-all-readmes
      - git add src/**/README.md
      - if ! git diff-index --quiet HEAD -- src/**/README.md; then
          git config --global user.name "nemobot";
          git config --global user.email "our-bots@buildo.io";
          git commit -m "Update READMES [skip CI]";
          git push origin master;
        fi
    when:
      branch: master

  gh-pages-build:
    image: quay.io/buildo/node5-npm3
    commands:
      - if [ "$$BRANCH" != "master" ]; then
          npm run generate-all-readmes
          npm run build-showroom;
        fi

  gh-pages:
    image: quay.io/buildo/node5-npm3
    commands:
      - git config --global user.email "ci@buildo.io"
      - git config --global user.name "Drone CI"
      - npm run deploy-showroom
    when:
      branch: master

cache:
  mount:
    - /drone/.npm
